### ISSUE TITLE
[Known issue] pade_approximant: GMP division by zero

### ISSUE THREAD

**Issue by mitsuaki1987** [issp-center-dev/DCore#3]
Dear users

If you face an error
```
pade_approximant: GMP division by zero
```
or your make-test fails at post_* tests, please try to apply the patch file
https://github.com/TRIQS/triqs/commit/0911876630d0d5939195104507c7e5f8b6615658.patch
to your **TRIQS** source directory as
``` bash
$ patch -p1 < patch-file
```
and rebuild **TRIQS**.

It is related to the issue
https://github.com/TRIQS/triqs/pull/544

Best regards,
Mitsuaki Kawamura

**Comment by shinaoka** [comment]
Merged into the triqs stable branch.
