### ISSUE TITLE
ALPS/cthybのbasis_rotation

### ISSUE THREAD

**Issue by mitsuaki1987** [issp-center-dev/DCore#4]
@shinaoka 

おそらくまだ正式サポート外だと思うのですが、ALPSCore-TRIQS-interfaceのオプションbasis_rotation=1を使ってみたいと考えています。
interface内ではbasis_rotationを使うとcthybに渡すパラメータrot_mat_Re,rot_mat_Imを変更していますが、
ALPSCore/cthybのリポジトリを見てみると、developやmasterではこのパラメータを使っておらず、ir_basisとir_basis_randomでは使っているようです。
そこで質問なのですが、ちょっと動かしてみようと思ったときに、ir_basisとir_basis_randomのどちらを使ったらよいですか？

**Comment by shinaoka** [comment]
すみません、研究会中なので明後日以降の対応になります。
ir_basis, ir_basis_randomは一年以上前に書いた私のテストコートです。
両方ともサポート外ですし、今となってはまともに動作しないと思います。

どういうユースケースか教えていただければ、対応可能だと思います。

**Comment by mitsuaki1987** [comment]
@shinaoka 
承知しました。大体わかったので、とりあえず自分で作ってみます。

**Comment by shinaoka** [comment]
rot_matというのが、摂動展開に使う一粒子基底への射影行列になっています。
デフォルトは単位行列ですが、それを変更することで負符号率を改善可能です。
一方、計算結果のグリーン関数は、ALPSCore/CT-HYBで逆基底変換をされた後のものが、
ALPSCore/CT-HYBから戻ってくるはずです。
(結果は常に、モデルの定義に使った一粒子基底で戻るように設計されています)

疑問点があればどうぞ。
