### ISSUE TITLE
Access/postprocessing of GF

### ISSUE THREAD

**Issue by chrisewolf** [issp-center-dev/DCore#5]
Dear all,

first of all, great tool! A serious upgrade in terms of usability compared to the bare TRIQS!

I am currently trying the Quantum espresso -> Wannier90 -> dcore route and it is working fairly well, thanks to the examples provided. But I was wondering about a post-processing approach to calculate useful "observables", such as L,S,J etc. I am expecting that DMFT will improve the values over DFT (well, it cannot get much worse than DFT ;) but so far I am unclear on how to access or post-process the output of dcore.

Sorry, this is a very basic question - I hope someone can give me some pointers nevertheless!

Best wishes from Spain,
Chris

**Comment by mitsuaki1987** [comment]
Dear chrisewolf

Hello,
The orbital angular momentum is difficult to treat in DCore. We only can estimate roughly it by using
 * Projector used for Wannier90
 * Density matrix printed in the standard output of DCoer
Unfortunately, the tool for this calculation is not provided.

Best regards,
Mitsuaki Kawamura

**Comment by chrisewolf** [comment]
Dear Mitsuaki san,

Thank you for your swift reply, I will look into the options you mentioned!

Best,
Chris
