### ISSUE TITLE
t2g with spin-orbit

### ISSUE THREAD

**Issue by kyohn1004** [issp-center-dev/DCore#6]
Dear all,

I have two questions.
Could you give me some advice?

(1) When considering spin-orbit in t2g system, I create a Hamiltonian in the following order.
Is the order correct?
- |xy,↑>
- |yz,↑>
- |xz,↑>
- |xy,↓>
- |yz,↓>
- |xz,↓>

(2) I want to use [interaction = slater_uj]. (I have checked dcore_pre.py)
If I type below, does dcore_pre form an interaction matrix in the order mentioned in (1)?
- norb = 6
- spin_orbit = True
- interaction = slater_uj
- slater_uj = [(2, 3.0, 1.0)]

Thank you for providing this nice tool.
Have a nice day!

Kyohoon

**Comment by kyohn1004** [comment]
Dear Mitsuaki,

Thank you for your quick reply.
Many thanks :)

Kyohoon

**Comment by kyohn1004** [comment]
May I ask you one more question..?
I used the following ini file:

[model]
lattice = wannier90
seedname = test
nelec = 4.0
ncor = 1
norb = 6
spin_orbit = True
interaction = slater_uj
slater_uj = [(2,3.0,1.0)]
bvec=[(-0.75,0.75,0.75),(0.75,-0.75,0.75),(0.75,0.75,-0.75)]
[system]
nk0 = 16
nk1 = 16
nk2 = 16
beta = 40.0
mu = 0.0
with_dc = True
perform_tail_fit = True
fit_max_moment = 8
fit_min_w = 5.0
fit_max_w = 19.0
[impurity_solver]
name = ALPS/cthyb
max_time{int} = 600
...

dcore_pre runs without error messages.
However, the following error appears in dcore.
- U_val = U_matrix[orb_names.index(a1),orb_names.index(a2),orb_names.index(a3),orb_names.index(a4)]
- IndexError: too many indices for array

Could you please comment on how to avoid this?

**Comment by mitsuaki1987** [comment]
Dear @kyohn1004
Sorry, it is a bug in the U-matrix construction for slater_uj case. Index for shell is absent.
I fixed it in the develop branch.
Thank you for reporting.
Best regards,
Mitsuaki Kawamura

**Comment by kyohn1004** [comment]
Dear Mitsuaki,

I checked your update for the two lines in [dcore_pre.py].
I applied it, and now the code works very well.
Thank you again :)

Kyohoon
