### ISSUE TITLE
tail-fit and complex GF

### ISSUE THREAD

**Issue by kyohn1004** [issp-center-dev/DCore#7]
Dear all,

I have a question about tail-fit.

In my case:
Without spin-orbit, tail-fit works fine.
With spin-orbit, I always receive the following message.
- more arguments are needed to fit a complex gf

====================

I think that above message is not a problem with dcore,
It would be an issue of triqs v1.4.
- https://github.com/TRIQS/cthyb/issues/83 : The real cause of the error is however a tiny imaginary part of Delta(tau), which can grow slowly with the DMFT iterations.

I would like to apply the method given below,
but I'm not sure if dcore treats g_tau.
- https://github.com/TRIQS/dft_tools/issues/106

====================

Currently I am using the Legendre-filter method instead of tail-fit.
However in my case, it seems unsuitable for self-consistent calculations
especially for the Mott-insulating systems.

Sometimes self-energy(iw) converges to a non-physical form,
and even the imaginary part goes up in the positive region.

====================

If you have ever tried to fix the problem and run tail-fit,
could you give me a comment?

Best regards,
Kyohoon

**Comment by shinaoka** [comment]
Hi.
This seems to be an issue in TRIQS 1.4.
DCore does not support TRIQS 2.0, which requires C++17.

Personally, I've been using ALPS/CT-HYB without tail fitting (with more Matsuabra frequencies).
The high-frequency part of the self-energy may be almost irrelevant in your calculations.
(as long as the low-frequency part is converged)
> Sometimes self-energy(iw) converges to a non-physical form,
> and even the imaginary part goes up in the positive region.

**Comment by kyohn1004** [comment]
Dear Shinaoka,

Thank you very much for your comment.
Now I am testing with ALPS/CT-HYB.
(also with more Matsubara frequencies and longer QMC run)

And the result is much better!
My problem seems to be solved without tail-fit.

Many thanks :)

Kyohoon
