### ISSUE TITLE
The Delta(tau) block number 0 is not real in tau space when using CTHYB

### ISSUE THREAD

**Issue by chrisewolf** [issp-center-dev/DCore#8]
Dear all,

I am working on Fe on MgO; the Fe:3d are the states of interest. In total I have 200 electrons in my system and the desired target occupancy of Fe:3d would be around 6. A similar work was done in Phys. Rev. B 93 140101 (R) 2016

Dcore seems to be working well when using the Hubbard-I solver (judging from dcore_check) however I cannot get a single iteration when switching to CTHYB because the program will always crash 
```

99.749820 < Total Density < 200.000322
    -0.249700 < Chemical Potential < -0.247862
    199.749820 < Total Density < 200.000007
    Chemical Potential found in 6 iterations : 
    Total Density = 200.000007;Chemical Potential = -0.247862
...
..
.
.. Error .. calling C++ overload 
.. solve() -> void 
.. in implementation of method SolverCore.solve
.. C++ error was : 
.. Triqs runtime error at /opt/triqs-1.4/cthyb-1.4.2/c++/./qmc_data.hpp : 87

The Delta(tau) block number 0 is not real in tau space
.. Error occurred on node 3

```

is there a way to overcome this? I played with the solver parameters quite a bit but it does not seem to affect the outcome.

The input is below!

Thanks for your help in advance - 
Best,
Chris

```
[model]
lattice = wannier90
seedname = FeOMg
nelec = 200
ncor = 1
norb = 5
kanamori = [(6.0, 0.0, 1.0)]
bvec=[(0.73847454899, 0.00, 0.0),(0.0, 0.73847454899, 0.0),(0.0, 0.0, 0.24615823223)]


[system]
nk0 = 3
nk1 = 3
nk2 = 1
beta = 100.0
mu =  -0.2497 
with_dc = true
n_iw = 1000
perform_tail_fit = false
fit_max_moment = 2
fit_min_w = 6.0
fit_max_w = 15.0

[impurity_solver]
name = TRIQS/cthyb
n_cycles{int} = 1000000
n_warmup_cycles{int} = 10000
length_cycle{int} = 1000
move_double{bool} = true
verbosity{int} = 10


[control]
max_step = 10000
restart = false

[tool]
broadening = 0.1
nk_line = 50
nnode = 4
knode=[(G,0.0,0.0,0.0),(X,0.0,0.5,0.0),(L,0.5,0.5,0.0),(G,0.0,0.0,0.0)]
omega_max =2.0
omega_min =-10.0
Nomega = 101
```

**Comment by shinaoka** [comment]
I guess that your build of triqs/cthyb was not configured with "-DHYBRIDISATION_IS_COMPLEX=ON -DLOCAL_HAMILTONIAN_IS_COMPLEX=ON".

Please refer to this page.
https://issp-center-dev.github.io/DCore/install.html

**Comment by j-otsuki** [comment]
Is this issue still active?

**Comment by shinaoka** [comment]
No. This issue is described in the documentation.
